In [1]:
#tutorial pytorch


In [2]:
import torch

In [3]:
###########################
##
##1ra parte: tensores
##
##########################

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

Using cuda device


In [7]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float32, device = device, requires_grad=True)
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])
True


In [34]:
#otra forma de iniciar un tensor
x = torch.empty(size=(3,3)) #inicia con valores aleatorios
print(x)
x= torch.zeros(size = (3,3)) #no es necesario el size
print(x)
x = torch.rand((3,3))
print(x)
x = torch.ones((3,3))
print(x)
x = torch.eye(5,5) # matriz identidad, eye es porque suena a I (identity)
print(x)
x = torch.arange(start=0, end = 5, step = 1)
print(x)
x = torch.linspace(start = 0.1, end = 1, steps = 10) #parte en 0.1, termina en 1 y tendra 10 valores intermedios (incluiyendo 0.1 y 1)
print(x)
x = torch.empty(size = (1,5)).normal_(mean=0, std= 1) #al inicio vimos que iniciaba con valores aleatorios, aca le damos una distribuicion, media y desviacion
print(x)
x = torch.empty(size = (1,5)).uniform_(0,1) #distro uniforme
print(x)
x = torch.diag((torch.ones(3))) #esencialmente es otra forma de hacer la identidad de 3x3
print(x)

#iniciar y convertir entre distintos tipos (int, float, double)
tensor = torch.arange(4)
print(tensor.bool()) #numeros > 0 seran true
print(tensor.short()) #int16
print(tensor.long()) #int64
print(tensor.half()) #float16
print(tensor.float()) #float32, uno de los mas usados
print(tensor.double()) #float64


tensor([[5.4845e-30, 0.0000e+00, 9.3862e-31],
        [4.4493e-41, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.9138, 0.9097, 0.2084],
        [0.7386, 0.3556, 0.2036],
        [0.3187, 0.9254, 0.6875]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[-0.3312, -0.1585,  2.0747, -0.5291, -0.1167]])
tensor([[0.0074, 0.8844, 0.4609, 0.1613, 0.9754]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0

In [38]:
#convertir de numpy a ternsor
import numpy as np
np_array = np.zeros((5,5))
tensor = torch.from_numpy(np_array)
print(tensor)
np_array_back = tensor.numpy()
print(np_array_back)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [54]:
#tensor maths
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

#suma, hay varias rformas
z1 = torch.empty(3)
torch.add(x,y,out=z1)
print(z1)

z2 = torch.add(x,y)
print(z2)

z = x + y
print(z)

#resta tambien hay varias, la mas directa
z = x-y
print(z)

#division
z = torch.true_divide(x,y) #(1/9,2/8, 3/7)
print(z)

########################
#
# operaciones "inplace"
#
#########################
t = torch.zeros(3)
t.add_(x)
print(t)
t += x
print(t)

#exponenciacion
z = x.pow(2)
print(z)

z = x **2
print(z)

#division
z = x.div(y)
print(z)

#multiplicacion
z = x.mul(y)
print(z)





tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([10, 10, 10])
tensor([-8, -6, -4])
tensor([0.1111, 0.2500, 0.4286])
tensor([1., 2., 3.])
tensor([2., 4., 6.])
tensor([1, 4, 9])
tensor([1, 4, 9])
tensor([0.1111, 0.2500, 0.4286])
tensor([ 9, 16, 21])


In [57]:
###################################
#
# comparaciones
#
####################################
z = x > 0
print(z)
z = x < 0
print(z)

tensor([True, True, True])
tensor([False, False, False])


In [67]:
#multiplicacion de matrices
x1 = torch.rand((2,5))
x2 = torch.rand((5,3)) #2x3
x3 = torch.mm(x1,x2) #mm matrix multiplication
print(x3)
x3 = x1.mm(x2)
print(x3)

#exponenciacion de matrices
matrix_exp = torch.rand((5,5))
print(matrix_exp)
matrix_exp = matrix_exp.matrix_power(3)
print(matrix_exp)

#multiplicacion elemento a elemento (element wise mult: ((a,b),(c,d)) x ((a',b'),(c',d')) = ((a*a',b*b'),(c*c',d*d'))
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
z = x * y
print(z)

#producto cruz (dot product)
z = torch.dot(x,y)
print(z)

#multiplicacion de matrices por lotes (batch matrix multipliocation)
batch = 32
n = 10
m = 20
p = 30
tensor1 =torch.rand((batch, n,m))
print(tensor1)
tensor2 =torch.rand((batch, m,p))

out_bbmm = torch.bmm(tensor1, tensor2)
print(out_bbmm)


tensor([[1.0430, 1.2644, 0.6688],
        [0.5185, 0.8411, 0.5691]])
tensor([[1.0430, 1.2644, 0.6688],
        [0.5185, 0.8411, 0.5691]])
tensor([[0.9955, 0.2843, 0.0622, 0.7430, 0.8556],
        [0.4037, 0.1303, 0.5596, 0.6224, 0.6776],
        [0.7501, 0.3609, 0.6338, 0.6006, 0.7045],
        [0.2071, 0.8176, 0.1297, 0.4206, 0.6069],
        [0.2691, 0.9119, 0.5374, 0.6201, 0.9638]])
tensor([[3.8488, 4.5817, 3.0848, 4.9306, 6.4311],
        [3.2329, 3.6902, 2.6403, 4.0701, 5.2769],
        [4.1825, 4.7704, 3.2315, 5.1770, 6.7327],
        [2.7433, 3.3068, 2.3288, 3.4832, 4.5534],
        [4.3217, 5.0682, 3.6248, 5.4353, 7.0796]])
tensor([ 9, 16, 21])
tensor(46)
tensor([[[0.3786, 0.8242, 0.9243,  ..., 0.3061, 0.5323, 0.6969],
         [0.5432, 0.0441, 0.3426,  ..., 0.5332, 0.3863, 0.2835],
         [0.4546, 0.6013, 0.8882,  ..., 0.0953, 0.6560, 0.4104],
         ...,
         [0.7699, 0.2883, 0.4273,  ..., 0.6530, 0.5895, 0.7312],
         [0.7142, 0.3068, 0.5361,  ..., 0.9945, 0.3004

In [71]:
#ejemplo de broadcasting
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

#matematicamente no tiene sentido restar una matriz menos un vector, pero si en pytorch
#porque expanden el vector para que calkse con las filas de x1, y a eso se refiere
#el termino broadcasting
z = x1-x2
print(z)

z = x1 ** x2
print(z)

tensor([[ 0.1372, -0.7495, -0.8277,  0.7091, -0.0548],
        [ 0.4916, -0.6721, -0.0845,  0.3957, -0.6009],
        [ 0.3117, -0.5124, -0.1498,  0.9053, -0.0183],
        [ 0.6162, -0.6733, -0.6807,  0.5823, -0.6018],
        [ 0.7203,  0.0091, -0.5009,  0.5864, -0.0870]])
tensor([[0.8934, 0.1246, 0.1712, 0.9830, 0.8289],
        [0.9595, 0.2169, 0.9140, 0.9492, 0.3122],
        [0.9333, 0.3866, 0.8488, 0.9982, 0.8612],
        [0.9734, 0.2155, 0.3183, 0.9712, 0.3112],
        [0.9834, 0.8653, 0.4981, 0.9716, 0.8004]])


In [101]:
#otras operaciones utiles
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
#suma de los elementos
sum_x = torch.sum(x, dim=0) # 0 xq es 1 vector
print(sum_x)
values, indices = torch.max(x, dim=0 )
print(values, indices)
values, indices = torch.min(x, dim=0 )
print(values, indices)
abs_x = torch.abs(x) #valor absoluto
print(abs_x)
z = torch.argmax(x, dim=0) #lo mismo que torch.max pero solo retorna el indice
print(z)
z = torch.argmin(x, dim=0) #lo mismo que torch.minx pero solo retorna el indice
print(z)
mean_x = torch.mean(x.float(), dim = 0) #requiere que sea float
print(mean_x)
#comparar si 2 elementos son iguales
z = torch.eq(x,y)
print(z)

#sort
sorted_y, indices = torch.sort(y, dim = 0, descending = False) # retorna sorted y el indice de posicion anterior
print(sorted_y, indices)

#compara todos los elementos menores que cero y los vuelve cero y sobre 10 los convierte a 10, pero el argumento max no es necesario
z = torch.clamp(x, min = 0, max=10 )
print(z)

x = torch.tensor([1,0,1,1,1], dtype = torch.bool)
print(x)
z = torch.any(x) #si al menos 1 es true retorna true
print(z)
z = torch.all(x) #si todo true retorna true, sino false
print(z)

tensor(6)
tensor(3) tensor(2)
tensor(1) tensor(0)
tensor([1, 2, 3])
tensor(2)
tensor(0)
tensor(2.)
tensor([False, False, False])
tensor([7, 8, 9]) tensor([2, 1, 0])
tensor([1, 2, 3])
tensor([ True, False,  True,  True,  True])
tensor(True)
tensor(False)


In [126]:
#indices de tensores
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

print(x[0].shape) # lo mismo que x[0,:]

print(x[:,0].shape)
print(x[2,0:10])
x[0,0] = 100

x =torch.arange(10)
indices = [2,5,8]
print(x[indices])

x = torch.rand((3,5))

rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x)
print(x[rows, cols])

#indexacion mas avanzada
x = torch.arange(10)
print(x)
print(x[(x < 2) | (x > 8)])
print(x[x.remainder(2) == 0]) #modulo 2 == 0



torch.Size([25])
torch.Size([10])
tensor([0.5075, 0.5146, 0.9790, 0.1086, 0.7360, 0.4482, 0.6863, 0.7858, 0.1259,
        0.5855])
tensor([2, 5, 8])
tensor([[0.3760, 0.9041, 0.7426, 0.9715, 0.5437],
        [0.7841, 0.1793, 0.8296, 0.2677, 0.0984],
        [0.6695, 0.6297, 0.3794, 0.8832, 0.8665]])
tensor([0.0984, 0.3760])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])


In [133]:
#operaciones utiles

print(torch.where(x > 5, x, x*2)) # si el valor es > 5 retorno el valor, sino el valor x2
print(torch.tensor([0,0,1,1,2,2,3,4]).unique()) #elementos unicos
x = torch.arange(10)
print(x.ndimension()) #1 sola dimension
print(x.numel()) #numero de elementos en x

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


In [164]:
# remodelar (reshape)
x = torch.arange(9) #lo convertiremos en 3x3
print(x)
x_3x3 = x.view(3,3)
print(x_3x3)
x_3x3 = x.reshape(3,3)
print(x_3x3)
#view y reshape son similares, view trabaja con tensores contiguos en memoria, reshape no importa xcq hara una copia
#por eso reshape es mas seguro, porque puede tirar errores a veces cuando se hacen mas operaciones como
#trasponer y luego hacer view(9)

#y = x_3x3.t()
#print(y)
#print(y.view(9))
#RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
print(x1)
print(x2)
print(torch.cat((x1,x2), dim=0).shape) #cat de concatenar
print(torch.cat((x1,x2), dim=1).shape) #cat de concatenar

z = x1.view(-1) #esto es magia xD sirve para aplanar (flatten) el tensor
print(x1)
print(z)

batch = 64
x = torch.rand((batch, 2, 5,5))
print(x.shape)
z = x.view(batch,-1)
print(z.shape)

x = torch.arange(10)
print(x.unsqueeze(0)) #Returns a new tensor with a dimension of size one inserted at the specified position
print(x.unsqueeze(1))

x = torch.arange(10).unsqueeze(0).unsqueeze(1) #1xx1x10
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0.7410, 0.1580, 0.8295, 0.2233, 0.2552],
        [0.9794, 0.1956, 0.1242, 0.9615, 0.0320]])
tensor([[0.0138, 0.7835, 0.5817, 0.6929, 0.1347],
        [0.9367, 0.9354, 0.1527, 0.3859, 0.1143]])
torch.Size([4, 5])
torch.Size([2, 10])
tensor([[0.7410, 0.1580, 0.8295, 0.2233, 0.2552],
        [0.9794, 0.1956, 0.1242, 0.9615, 0.0320]])
tensor([0.7410, 0.1580, 0.8295, 0.2233, 0.2552, 0.9794, 0.1956, 0.1242, 0.9615,
        0.0320])
torch.Size([64, 2, 5, 5])
torch.Size([64, 50])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])
