In [1]:
#tutorial pytorch


In [2]:
import torch


In [3]:
###########################
##
##1ra parte: tensores
##
##########################

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

Using cpu device


In [5]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float32, device = device, requires_grad=True)
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.float32
cpu
torch.Size([2, 3])
True


In [6]:
#otra forma de iniciar un tensor
x = torch.empty(size=(3,3)) #inicia con valores aleatorios
print(x)
x= torch.zeros(size = (3,3)) #no es necesario el size
print(x)
x = torch.rand((3,3))
print(x)
x = torch.ones((3,3))
print(x)
x = torch.eye(5,5) # matriz identidad, eye es porque suena a I (identity)
print(x)
x = torch.arange(start=0, end = 5, step = 1)
print(x)
x = torch.linspace(start = 0.1, end = 1, steps = 10) #parte en 0.1, termina en 1 y tendra 10 valores intermedios (incluiyendo 0.1 y 1)
print(x)
x = torch.empty(size = (1,5)).normal_(mean=0, std= 1) #al inicio vimos que iniciaba con valores aleatorios, aca le damos una distribuicion, media y desviacion
print(x)
x = torch.empty(size = (1,5)).uniform_(0,1) #distro uniforme
print(x)
x = torch.diag((torch.ones(3))) #esencialmente es otra forma de hacer la identidad de 3x3
print(x)

#iniciar y convertir entre distintos tipos (int, float, double)
tensor = torch.arange(4)
print(tensor.bool()) #numeros > 0 seran true
print(tensor.short()) #int16
print(tensor.long()) #int64
print(tensor.half()) #float16
print(tensor.float()) #float32, uno de los mas usados
print(tensor.double()) #float64


tensor([[3.0451e-34, 0.0000e+00, 0.0000e+00],
        [2.0000e+00, 0.0000e+00, 2.1250e+00],
        [0.0000e+00, 2.2500e+00, 0.0000e+00]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.0791, 0.2653, 0.8128],
        [0.7762, 0.7146, 0.9603],
        [0.7174, 0.1427, 0.4655]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[-0.6095, -0.5598,  0.2538,  1.5329,  0.2659]])
tensor([[0.4545, 0.5468, 0.3124, 0.8833, 0.7467]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0

In [7]:
#convertir de numpy a ternsor
import numpy as np
np_array = np.zeros((5,5))
tensor = torch.from_numpy(np_array)
print(tensor)
np_array_back = tensor.numpy()
print(np_array_back)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
#tensor maths
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

#suma, hay varias rformas
z1 = torch.empty(3)
torch.add(x,y,out=z1)
print(z1)

z2 = torch.add(x,y)
print(z2)

z = x + y
print(z)

#resta tambien hay varias, la mas directa
z = x-y
print(z)

#division
z = torch.true_divide(x,y) #(1/9,2/8, 3/7)
print(z)

########################
#
# operaciones "inplace"
#
#########################
t = torch.zeros(3)
t.add_(x)
print(t)
t += x
print(t)

#exponenciacion
z = x.pow(2)
print(z)

z = x **2
print(z)

#division
z = x.div(y)
print(z)

#multiplicacion
z = x.mul(y)
print(z)





tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([10, 10, 10])
tensor([-8, -6, -4])
tensor([0.1111, 0.2500, 0.4286])
tensor([1., 2., 3.])
tensor([2., 4., 6.])
tensor([1, 4, 9])
tensor([1, 4, 9])
tensor([0.1111, 0.2500, 0.4286])
tensor([ 9, 16, 21])


In [9]:
###################################
#
# comparaciones
#
####################################
z = x > 0
print(z)
z = x < 0
print(z)

tensor([True, True, True])
tensor([False, False, False])


In [10]:
#multiplicacion de matrices
x1 = torch.rand((2,5))
x2 = torch.rand((5,3)) #2x3
x3 = torch.mm(x1,x2) #mm matrix multiplication
print(x3)
x3 = x1.mm(x2)
print(x3)

#exponenciacion de matrices
matrix_exp = torch.rand((5,5))
print(matrix_exp)
matrix_exp = matrix_exp.matrix_power(3)
print(matrix_exp)

#multiplicacion elemento a elemento (element wise mult: ((a,b),(c,d)) x ((a',b'),(c',d')) = ((a*a',b*b'),(c*c',d*d'))
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
z = x * y
print(z)

#producto cruz (dot product)
z = torch.dot(x,y)
print(z)

#multiplicacion de matrices por lotes (batch matrix multipliocation)
batch = 32
n = 10
m = 20
p = 30
tensor1 =torch.rand((batch, n,m))
print(tensor1)
tensor2 =torch.rand((batch, m,p))

out_bbmm = torch.bmm(tensor1, tensor2)
print(out_bbmm)


tensor([[1.7587, 1.3107, 0.4490],
        [1.0203, 0.6216, 0.3288]])
tensor([[1.7587, 1.3107, 0.4490],
        [1.0203, 0.6216, 0.3288]])
tensor([[0.9701, 0.6094, 0.5127, 0.4896, 0.1436],
        [0.6943, 0.9744, 0.6586, 0.9985, 0.0340],
        [0.1774, 0.9658, 0.7351, 0.0758, 0.6709],
        [0.5973, 0.8901, 0.3886, 0.4905, 0.9395],
        [0.6017, 0.0877, 0.4440, 0.5506, 0.5430]])
tensor([[5.0163, 6.0437, 4.4896, 4.4203, 3.2824],
        [6.4086, 7.7167, 5.7715, 5.8204, 4.2524],
        [4.4695, 5.6780, 4.1699, 3.9859, 3.2965],
        [5.8403, 6.9611, 5.1656, 5.0059, 4.1570],
        [3.8363, 4.3131, 3.4004, 3.3224, 2.5931]])
tensor([ 9, 16, 21])
tensor(46)
tensor([[[0.9253, 0.6216, 0.0870,  ..., 0.3235, 0.2182, 0.6038],
         [0.5770, 0.4125, 0.4155,  ..., 0.8245, 0.2182, 0.7172],
         [0.3053, 0.3932, 0.8221,  ..., 0.9512, 0.5634, 0.1133],
         ...,
         [0.9302, 0.3663, 0.3147,  ..., 0.6456, 0.7483, 0.9207],
         [0.0365, 0.1933, 0.2288,  ..., 0.8426, 0.5965

In [11]:
#ejemplo de broadcasting
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

#matematicamente no tiene sentido restar una matriz menos un vector, pero si en pytorch
#porque expanden el vector para que calkse con las filas de x1, y a eso se refiere
#el termino broadcasting
z = x1-x2
print(z)

z = x1 ** x2
print(z)

tensor([[ 0.4706,  0.1105,  0.0723,  0.5817, -0.1750],
        [-0.2056,  0.7370,  0.0266, -0.3236,  0.2855],
        [-0.1076,  0.4572,  0.2746, -0.3530, -0.1681],
        [-0.2850,  0.6291, -0.2891,  0.4056,  0.6099],
        [ 0.5067,  0.1692, -0.0600,  0.3829,  0.6298]])
tensor([[0.9764, 0.8278, 0.7470, 0.9868, 0.5000],
        [0.5378, 0.9817, 0.7168, 0.3406, 0.8619],
        [0.6226, 0.9319, 0.8658, 0.2639, 0.5176],
        [0.4566, 0.9644, 0.4406, 0.9134, 0.9594],
        [0.9940, 0.8520, 0.6550, 0.9032, 0.9644]])


In [12]:
#otras operaciones utiles
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
#suma de los elementos
sum_x = torch.sum(x, dim=0) # 0 xq es 1 vector
print(sum_x)
values, indices = torch.max(x, dim=0 )
print(values, indices)
values, indices = torch.min(x, dim=0 )
print(values, indices)
abs_x = torch.abs(x) #valor absoluto
print(abs_x)
z = torch.argmax(x, dim=0) #lo mismo que torch.max pero solo retorna el indice
print(z)
z = torch.argmin(x, dim=0) #lo mismo que torch.minx pero solo retorna el indice
print(z)
mean_x = torch.mean(x.float(), dim = 0) #requiere que sea float
print(mean_x)
#comparar si 2 elementos son iguales
z = torch.eq(x,y)
print(z)

#sort
sorted_y, indices = torch.sort(y, dim = 0, descending = False) # retorna sorted y el indice de posicion anterior
print(sorted_y, indices)

#compara todos los elementos menores que cero y los vuelve cero y sobre 10 los convierte a 10, pero el argumento max no es necesario
z = torch.clamp(x, min = 0, max=10 )
print(z)

x = torch.tensor([1,0,1,1,1], dtype = torch.bool)
print(x)
z = torch.any(x) #si al menos 1 es true retorna true
print(z)
z = torch.all(x) #si todo true retorna true, sino false
print(z)

tensor(6)
tensor(3) tensor(2)
tensor(1) tensor(0)
tensor([1, 2, 3])
tensor(2)
tensor(0)
tensor(2.)
tensor([False, False, False])
tensor([7, 8, 9]) tensor([2, 1, 0])
tensor([1, 2, 3])
tensor([ True, False,  True,  True,  True])
tensor(True)
tensor(False)


In [13]:
#indices de tensores
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

print(x[0].shape) # lo mismo que x[0,:]

print(x[:,0].shape)
print(x[2,0:10])
x[0,0] = 100

x =torch.arange(10)
indices = [2,5,8]
print(x[indices])

x = torch.rand((3,5))

rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x)
print(x[rows, cols])

#indexacion mas avanzada
x = torch.arange(10)
print(x)
print(x[(x < 2) | (x > 8)])
print(x[x.remainder(2) == 0]) #modulo 2 == 0



torch.Size([25])
torch.Size([10])
tensor([0.3164, 0.3998, 0.7438, 0.5359, 0.6174, 0.5521, 0.6333, 0.5623, 0.3949,
        0.3723])
tensor([2, 5, 8])
tensor([[0.4321, 0.0791, 0.1008, 0.8981, 0.7324],
        [0.1863, 0.5856, 0.0690, 0.3647, 0.4594],
        [0.9666, 0.6111, 0.1921, 0.3804, 0.4444]])
tensor([0.4594, 0.4321])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])


In [14]:
#operaciones utiles

print(torch.where(x > 5, x, x*2)) # si el valor es > 5 retorno el valor, sino el valor x2
print(torch.tensor([0,0,1,1,2,2,3,4]).unique()) #elementos unicos
x = torch.arange(10)
print(x.ndimension()) #1 sola dimension
print(x.numel()) #numero de elementos en x

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


In [15]:
# remodelar (reshape)
x = torch.arange(9) #lo convertiremos en 3x3
print(x)
x_3x3 = x.view(3,3)
print(x_3x3)
x_3x3 = x.reshape(3,3)
print(x_3x3)
#view y reshape son similares, view trabaja con tensores contiguos en memoria, reshape no importa xcq hara una copia
#por eso reshape es mas seguro, porque puede tirar errores a veces cuando se hacen mas operaciones como
#trasponer y luego hacer view(9)

#y = x_3x3.t()
#print(y)
#print(y.view(9))
#RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
print(x1)
print(x2)
print(torch.cat((x1,x2), dim=0).shape) #cat de concatenar
print(torch.cat((x1,x2), dim=1).shape) #cat de concatenar

z = x1.view(-1) #esto es magia xD sirve para aplanar (flatten) el tensor
print(x1)
print(z)

batch = 64
x = torch.rand((batch, 2, 5,5))
print(x.shape)
z = x.view(batch,-1)
print(z.shape)

x = torch.arange(10)
print(x.unsqueeze(0)) #Returns a new tensor with a dimension of size one inserted at the specified position
print(x.unsqueeze(1))

x = torch.arange(10).unsqueeze(0).unsqueeze(1) #1xx1x10
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0.1443, 0.8832, 0.9177, 0.1913, 0.2832],
        [0.4397, 0.6387, 0.5466, 0.8864, 0.8141]])
tensor([[0.3929, 0.0498, 0.4543, 0.1167, 0.4053],
        [0.9646, 0.4426, 0.6723, 0.0685, 0.4420]])
torch.Size([4, 5])
torch.Size([2, 10])
tensor([[0.1443, 0.8832, 0.9177, 0.1913, 0.2832],
        [0.4397, 0.6387, 0.5466, 0.8864, 0.8141]])
tensor([0.1443, 0.8832, 0.9177, 0.1913, 0.2832, 0.4397, 0.6387, 0.5466, 0.8864,
        0.8141])
torch.Size([64, 2, 5, 5])
torch.Size([64, 50])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])


In [20]:
#gradientes (copiado de https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html)
x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
print(w)
b = torch.randn(3, requires_grad=True)
print(b)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
print(y,z, loss)
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-0.6518,  1.6231, -0.2330],
        [-0.6221,  0.3071, -0.4295],
        [ 0.3938, -1.5712,  1.6169],
        [ 1.7591, -0.5017, -1.1352],
        [ 0.7453, -0.3873,  1.0562]], requires_grad=True)
tensor([ 0.6038,  2.4329, -0.9644], requires_grad=True)
tensor([0., 0., 0.]) tensor([ 2.2281,  1.9029, -0.0888], grad_fn=<AddBackward0>) tensor(1.6740, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Gradient function for z = <AddBackward0 object at 0x7bce74a04190>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x7bcd9970a2f0>
tensor([[0.3009, 0.2901, 0.1593],
        [0.3009, 0.2901, 0.1593],
        [0.3009, 0.2901, 0.1593],
        [0.3009, 0.2901, 0.1593],
        [0.3009, 0.2901, 0.1593]])
tensor([0.3009, 0.2901, 0.1593])


In [21]:
#Disabling Gradient Tracking
#By default, all tensors with requires_grad=True are tracking their computational history and support gradient computation. However, there are some cases when we do not need to do that, for example,
#when we have trained the model and just want to apply it to some input data, i.e. we only want to do forward computations through the network. We can stop tracking computations by surrounding our
#computation code with torch.no_grad() block:

z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)


True
False
